version: '3'

services:
  webcat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - SERPER_API_KEY=${SERPER_API_KEY}
      - WEBCAT_API_KEY=${WEBCAT_API_KEY}
      - PORT=${PORT:-8000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_DIR=/var/log/webcat
    volumes:
      - ${LOG_DIR:-./logs}:/var/log/webcat
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Accept: text/event-stream", "http://localhost:${PORT:-8000}/mcp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 