# Docker Compose setup with nginx reverse proxy for authentication
#
# USAGE:
# 1. Set SERPER_API_KEY and WEBCAT_API_KEY in your environment or .env file
# 2. Run: docker-compose -f docker-compose-nginx.yml up -d
# 3. Access WebCat at: https://localhost:4000/mcp
# 4. Include header: Authorization: Bearer <WEBCAT_API_KEY>
#
# NOTE: WebCat runs on internal network without auth
#       Nginx validates bearer token before proxying to WebCat

version: '3.8'

services:
  webcat:
    image: tmfrisinger/webcat:latest
    environment:
      - SERPER_API_KEY=${SERPER_API_KEY}
      # DON'T set WEBCAT_API_KEY - nginx handles auth
    networks:
      - internal
    # Not exposed externally - only nginx can reach it

  nginx:
    image: nginx:alpine
    ports:
      - "4000:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - WEBCAT_API_KEY=${WEBCAT_API_KEY}  # For config templating
    networks:
      - internal
    depends_on:
      - webcat

networks:
  internal:
    driver: bridge
