services:
  webcat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SERPER_API_KEY=${SERPER_API_KEY}
      - PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_DIR=/var/log/webcat
      - WEBCAT_MODE=${WEBCAT_MODE:-demo}
    volumes:
      - ${LOG_DIR:-./logs}:/var/log/webcat
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
