name: Build and deploy Python project to Azure Function App - webcatgpt

on:
  push:
    branches:
      - azure-function
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'GptWithMe' # Adjusted to the path to your Azure Function project
  PYTHON_VERSION: '3.11' # Set this to the Python version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} && zip -r ../release.zip ./* 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'webcatgpt'
          slot-name: 'production'
          package: '.' # The artifact is unzipped at the root of the GitHub Action runner's filesystem
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1234 }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true

