name: Build and publish MCP Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker_mcp.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            webcat/mcp:latest
            webcat/mcp:${{ github.sha }}
          cache-from: type=registry,ref=webcat/mcp:buildcache
          cache-to: type=registry,ref=webcat/mcp:buildcache,mode=max 