name: Docker MCP Tests

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker_mcp.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker_mcp.yml'
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-mock pytest-asyncio pytest-timeout httpx
          pip install -e .

      - name: Run unit tests
        run: |
          cd docker
          PYTHONPATH=. python -m pytest -v -m "not integration"
        env:
          WEBCAT_API_KEY: test_key_for_ci  # pragma: allowlist secret
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}

      - name: Run integration tests (if server available)
        timeout-minutes: 3
        run: |
          cd docker
          # Try to run integration tests, but don't fail the build if server isn't available
          PYTHONPATH=. python -m pytest -v -m "integration" || echo "Integration tests skipped - no running server"
        env:
          WEBCAT_API_KEY: test_key_for_ci  # pragma: allowlist secret
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
