name: Build and deploy Python project to Azure Function App - webcatgpt

on:
  push:
    branches:
      - main
    paths:
      - 'customgpt/**'  # Only trigger when files in customgpt directory change
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'customgpt' # updated to the new path
  PYTHON_VERSION: '3.11' # set this to the python version to use

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt ]; then pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt; fi

      - name: Run tests
        run: |
          # Set Python path to include customgpt directory
          PYTHONPATH=$PYTHONPATH:$(pwd)/${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} pytest -v customgpt/tests/

  build:
    needs: test # Only run build if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/requirements.txt

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      # Removed unzip step to deploy zip file directly
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'webcatgpt'
          slot-name: 'Production'
          package: './release.zip' # Adjusted to deploy the content of src directly
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A0CFD2E02C29451F9ABF27C189B5721B }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
